#!/bin/bash

#input directory
cd /home/Rahul/Desktop/Thesis/Problem-Set/Misc


for i in *.py
{
	if [[ -f $j ]]; then
	echo $i
	#interpret 'Python' program
	/usr/bin/time -f "%e\t%M " python $i <ip
	fi	
}
